# Housing Rental Analysis for San Francisco

In [1]:
# Import the required libraries and dependencies
import numpy as np
import pandas as pd
import os

# Import the hvPlot library
import hvplot.pandas
import holoviews as hv

## Import the data 

In [2]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighborhoods_census_data.csv file from the Resources folder
sfo_data_df = pd.read_csv("sfo_neighborhoods_census_data.csv")

# Review the first and last five rows of the DataFrame
display(sfo_data_df.head())
display(sfo_data_df.tail())

year      neighborhood  sale_price_sqr_foot  housing_units  gross_rent
0  2010      Alamo Square           291.182945         372560        1239
1  2010        Anza Vista           267.932583         372560        1239
2  2010           Bayview           170.098665         372560        1239
3  2010  Buena Vista Park           347.394919         372560        1239
4  2010  Central Richmond           319.027623         372560        1239

year            neighborhood  sale_price_sqr_foot  housing_units  \
392  2016          Telegraph Hill           903.049771         384242   
393  2016              Twin Peaks           970.085470         384242   
394  2016  Van Ness/ Civic Center           552.602567         384242   
395  2016       Visitacion Valley           328.319007         384242   
396  2016           Westwood Park           631.195426         384242   

     gross_rent  
392        4390  
393        4390  
394        4390  
395        4390  
396        4390

---

## Calculating and Plotting the Housing Units per Year

### Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

In [3]:
# Create a numerical aggregation that groups the data by the year and then averages the results.
# The usage of numeric_only is required as the future versions will default to False
housing_units_by_year = sfo_data_df.groupby('year').mean(numeric_only=True)

# Review the DataFrame
housing_units_by_year.head()

sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0

### Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`. Style and format the line plot to ensure a professionally styled visualisation.

In [4]:
# Create a visual aggregation explore the housing units by year
housing_units_by_year.hvplot(kind='bar',
                            x="year", 
                            y="housing_units", 
                            xlabel = "Year",
                            ylabel = "Housing Units", 
                            yformatter = '%.0f',
                            ylim=(365000,385000),
                            title = "Housing Units in San Francisco Between 2010 to 2016"
                            )

:Bars   [year]   (housing_units)

### What is the overall trend in `housing units` over the period being analysed?

__The housing units have been increasing every year at a steady rate across the given timeframe.__

In [5]:
# Additional Analyses

#This analysis will help identify the years with the most significant growth and decline in housing units.

# Calculate percentage change
housing_units_by_year['pct_change'] = housing_units_by_year['housing_units'].pct_change() * 100

# Find the year with the highest increase and the year with the highest decrease
max_increase_year = housing_units_by_year.loc[housing_units_by_year['pct_change'].idxmax()]
max_decrease_year = housing_units_by_year.loc[housing_units_by_year['pct_change'].idxmin()]

print("Year with the Highest Increase in Housing Units:")
print(max_increase_year)

print("\nYear with the Highest Decrease in Housing Units:")
print(max_decrease_year)

Year with the Highest Increase in Housing Units:
sale_price_sqr_foot       341.903429
housing_units          374507.000000
gross_rent               1530.000000
pct_change                  0.522600
Name: 2011, dtype: float64

Year with the Highest Decrease in Housing Units:
sale_price_sqr_foot       697.643709
housing_units          384242.000000
gross_rent               4390.000000
pct_change                  0.509293
Name: 2016, dtype: float64


In [6]:
# Analyzing the range gives insights into the overall variation in housing units during the specified period.

# Calculate the difference between maximum and minimum housing units
max_housing_units = housing_units_by_year['housing_units'].max()
min_housing_units = housing_units_by_year['housing_units'].min()
housing_units_range = max_housing_units - min_housing_units

print("Maximum Housing Units:", max_housing_units)
print("Minimum Housing Units:", min_housing_units)
print("Housing Units Range:", housing_units_range)

Maximum Housing Units: 384242.0
Minimum Housing Units: 372560.0
Housing Units Range: 11682.0


---

## Calculate and Plot the Average Sale Prices per Square Foot

### Group the data by year, and then average the results.

In [7]:
# Create a numerical aggregation by grouping the data by year and averaging the results
prices_square_foot_by_year = sfo_data_df.groupby('year').mean(numeric_only=True)

# Review the resulting DataFrame
prices_square_foot_by_year.head()

sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0

### What is the lowest gross rent reported for the years included in the DataFrame?

__The lowest gross rent is reported in 2010 which is $1,239__

In [8]:
## This can also be done by

# Find the year and gross_rent where gross_rent is minimum
year_with_min_rent = prices_square_foot_by_year['gross_rent'].idxmin()
min_gross_rent = prices_square_foot_by_year['gross_rent'].min()

print(f"The minimum Gross Rent \033[1m${min_gross_rent}\033[0m was reported in the year \033[1m{year_with_min_rent}\033[0m")

The minimum Gross Rent $1239.0 was reported in the year 2010


### Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

In [9]:
# Filter out the housing_units column, creating a new DataFrame 
# Keep only sale_price_sqr_foot and gross_rent averages per year
prices_square_foot_by_year = prices_square_foot_by_year.drop(columns = "housing_units")

# Review the DataFrame
prices_square_foot_by_year.head()

sale_price_sqr_foot  gross_rent
year                                 
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0

### Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot. Style and format the line plot to ensure a professionally styled visualisation.

In [31]:
# Plot prices_square_foot_by_year. 
# Inclued labels for the x- and y-axes, and a title.
gross_rent_plot = prices_square_foot_by_year['gross_rent'].hvplot().opts(
    yformatter='%.0f',
    color="orange",
    hover_color="yellow"
)

sale_price_sqr_foot_plot = prices_square_foot_by_year['sale_price_sqr_foot'].hvplot().opts(
    yformatter='%.0f',
    color="blue",
    hover_color="yellow"
)

(gross_rent_plot * sale_price_sqr_foot_plot).opts(title = "Sale Price per Square foot and Average Gross Rent between 2010-2016 - San Francisco", 
                                                  xlabel = "Year", 
                                                  ylabel = "Gross Rent/Sale Price Per Square Foot", 
                                                  height = 500, 
                                                  width = 800, 
                                                  legend_position = "top_left")

:Overlay
   .Curve.Gross_rent          :Curve   [year]   (gross_rent)
   .Curve.Sale_price_sqr_foot :Curve   [year]   (sale_price_sqr_foot)

### Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

### Did any year experience a drop in the average sale price per square foot compared to the previous year? If so, did the gross rent increase or decrease during that year?

__It can be observed that 2011 experienced a decrease in average sale price per square foot, it dropped from \\$ 369.344 in 2010 to \\$ 341.903 in 2011__  
<br>
__The gross rent on the other hand increased from \\$ 1,239 to \\$ $1,530__

In [36]:
## This can also be done by

# Calculate percentage change for 'sale_price_sqr_foot'
prices_square_foot_by_year['sale_price_change'] = round(prices_square_foot_by_year['sale_price_sqr_foot'].pct_change() * 100, 2)

# Find the years where there was a decrease in sale_price_change
years_with_price_decrease = prices_square_foot_by_year[
    prices_square_foot_by_year['sale_price_change'] < 0
]

# Iterate through the years with a decrease in sale_price_change and compare gross_rent to the previous year
for year in years_with_price_decrease.index:
    sale_price_change = years_with_price_decrease.loc[year]['sale_price_change']
    gross_rent = years_with_price_decrease.loc[year]['gross_rent']
    
    # Find the gross rent of the previous year
    previous_year = year - 1
    previous_year_rent = prices_square_foot_by_year.loc[previous_year]['gross_rent']
    
    print(f"It can be observed that \033[1m{year}\033[0m experienced a decrease in average sale price per square foot, it dropped by \033[1m{sale_price_change}\033[0m%. Gross Rent that year was \033[1m${gross_rent}\033[0m and the previous year's Gross Rent was \033[1m${previous_year_rent}\033[0m")

It can be observed that 2011 experienced a decrease in average sale price per square foot, it dropped by -7.43%. Gross Rent that year was $1530.0 and the previous year's Gross Rent was $1239.0


---

## Compare the Average Sale Prices by Neighborhood

### Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the `mean` of the groups.

In [37]:
# Group by year and neighborhood and then create a new dataframe of the mean values
prices_by_year_by_neighborhood = sfo_data_df.groupby(['year','neighborhood']).mean(numeric_only=True)

# Review the DataFrame
prices_by_year_by_neighborhood.head()

sale_price_sqr_foot  housing_units  gross_rent
year neighborhood                                                    
2010 Alamo Square               291.182945       372560.0      1239.0
     Anza Vista                 267.932583       372560.0      1239.0
     Bayview                    170.098665       372560.0      1239.0
     Buena Vista Park           347.394919       372560.0      1239.0
     Central Richmond           319.027623       372560.0      1239.0

### Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

In [38]:
# Filter out the housing_units
prices_by_year_by_neighborhood = prices_by_year_by_neighborhood.drop(columns = 'housing_units')

# Review the first and last five rows of the DataFrame
display(prices_by_year_by_neighborhood.head())
display(prices_by_year_by_neighborhood.tail())

sale_price_sqr_foot  gross_rent
year neighborhood                                     
2010 Alamo Square               291.182945      1239.0
     Anza Vista                 267.932583      1239.0
     Bayview                    170.098665      1239.0
     Buena Vista Park           347.394919      1239.0
     Central Richmond           319.027623      1239.0

sale_price_sqr_foot  gross_rent
year neighborhood                                           
2016 Telegraph Hill                   903.049771      4390.0
     Twin Peaks                       970.085470      4390.0
     Van Ness/ Civic Center           552.602567      4390.0
     Visitacion Valley                328.319007      4390.0
     Westwood Park                    631.195426      4390.0

### Create an interactive line plot with hvPlot that visualises both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighborhood`. Style and format the line plot to ensure a professionally styled visualisation.

In [46]:
# Use hvplot to create an interactive line plot of the average price per square foot

prices_by_year_by_neighborhood.hvplot.line(x = "year", 
                                           y = ["sale_price_sqr_foot", "gross_rent"], 
                                           groupby = "neighborhood", 
                                           title = "Sale Price per Square foot and Average Gross Rent between 2010-2016 - By Neighborhood", 
                                           xlabel = "Year", 
                                           ylabel = "Gross Rent/Sale Price Per Square Foot", 
                                           height = 500, 
                                           width = 800).opts(legend_position = "top_left")

:DynamicMap   [neighborhood]
   :NdOverlay   [Variable]
      :Curve   [year]   (value)

### Use the interactive visualisation to answer the following question:

### For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012?

__The average sale price per square foot has decreased to \\$ 88.4 from \\$ 344.49__

In [48]:
## This can also be done by

# Filter the DataFrame to select only Anza Vista neighborhood for 2016 and 2012
anza_vista_2016 = prices_by_year_by_neighborhood.loc[(2016, 'Anza Vista')]
anza_vista_2012 = prices_by_year_by_neighborhood.loc[(2012, 'Anza Vista')]

# Extract the sale prices for 2016 and 2012
sale_price_2016 = anza_vista_2016['sale_price_sqr_foot']
sale_price_2012 = anza_vista_2012['sale_price_sqr_foot']

# Calculate the percentage change
percentage_change = ((sale_price_2016 - sale_price_2012) / sale_price_2012) * 100

# Print the results
print(f"Average Sale Price per Square Foot in Anza Vista (2016): \033[1m${sale_price_2016:.2f}\033[0m")
print(f"Average Sale Price per Square Foot in Anza Vista (2012): \033[1m${sale_price_2012:.2f}\033[0m")
print(f"Percentage Change: \033[1m{percentage_change:.2f}%\033[0m")

Average Sale Price per Square Foot in Anza Vista (2016): $88.40
Average Sale Price per Square Foot in Anza Vista (2012): $344.49
Percentage Change: -74.34%


---

## Build an Interactive Neighborhood Map

### Read the `neighborhood_coordinates.csv` file into the notebook, and create a DataFrame named `neighborhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighborhood”.

In [49]:
# Load neighborhoods coordinates data
neighborhood_locations_df = pd.read_csv("neighborhoods_coordinates.csv", index_col = "Neighborhood")

# Review the DataFrame
neighborhood_locations_df.head()

Lat         Lon
Neighborhood                          
Alamo Square     37.791012 -122.402100
Anza Vista       37.779598 -122.443451
Bayview          37.734670 -122.401060
Bayview Heights  37.728740 -122.410980
Bernal Heights   37.728630 -122.443050

### Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregate the results by the `mean` of the group.

In [50]:
# Calculate the mean values for each neighborhood
all_neighborhood_info_df = sfo_data_df.groupby('neighborhood').mean(numeric_only=True)

# Review the DataFrame
all_neighborhood_info_df.head()

year  sale_price_sqr_foot  housing_units   gross_rent
neighborhood                                                                 
Alamo Square     2013.000000           366.020712       378401.0  2817.285714
Anza Vista       2013.333333           373.382198       379050.0  3031.833333
Bayview          2012.000000           204.588623       376454.0  2318.400000
Bayview Heights  2015.000000           590.792839       382295.0  3739.000000
Bernal Heights   2013.500000           576.746488       379374.5  3080.333333

### Review the two code cells that concatenate the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame. 

Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighborhoods_df`. 

In [51]:
# Using the Pandas `concat` function, join the 
# neighborhood_locations_df and the all_neighborhood_info_df DataFrame
# The axis of the concatenation is "columns".
# The concat function will automatially combine columns with
# identical information, while keeping the additional columns.
all_neighborhoods_df = pd.concat(
    [neighborhood_locations_df, all_neighborhood_info_df], 
    axis="columns",
    sort=False
)

# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())

Lat         Lon         year  sale_price_sqr_foot  \
Alamo Square     37.791012 -122.402100  2013.000000           366.020712   
Anza Vista       37.779598 -122.443451  2013.333333           373.382198   
Bayview          37.734670 -122.401060  2012.000000           204.588623   
Bayview Heights  37.728740 -122.410980  2015.000000           590.792839   
Bernal Heights   37.728630 -122.443050          NaN                  NaN   

                 housing_units   gross_rent  
Alamo Square          378401.0  2817.285714  
Anza Vista            379050.0  3031.833333  
Bayview               376454.0  2318.400000  
Bayview Heights       382295.0  3739.000000  
Bernal Heights             NaN          NaN

Lat        Lon    year  sale_price_sqr_foot  \
Yerba Buena      37.79298 -122.39636  2012.5           576.709848   
Bernal Heights        NaN        NaN  2013.5           576.746488   
Downtown              NaN        NaN  2013.0           391.434378   
Ingleside             NaN        NaN  2012.5           367.895144   
Outer Richmond        NaN        NaN  2013.0           473.900773   

                 housing_units   gross_rent  
Yerba Buena           377427.5  2555.166667  
Bernal Heights        379374.5  3080.333333  
Downtown              378401.0  2817.285714  
Ingleside             377427.5  2509.000000  
Outer Richmond        378401.0  2817.285714

In [52]:
# Call the dropna function to remove any neighborhoods that do not have data
all_neighborhoods_df = all_neighborhoods_df.reset_index().dropna()

# Rename the "index" column as "Neighborhood" for use in the visualisation
all_neighborhoods_df = all_neighborhoods_df.rename(columns={"index": "Neighborhood"})

# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())

Neighborhood        Lat         Lon         year  sale_price_sqr_foot  \
0      Alamo Square  37.791012 -122.402100  2013.000000           366.020712   
1        Anza Vista  37.779598 -122.443451  2013.333333           373.382198   
2           Bayview  37.734670 -122.401060  2012.000000           204.588623   
3   Bayview Heights  37.728740 -122.410980  2015.000000           590.792839   
5  Buena Vista Park  37.768160 -122.439330  2012.833333           452.680591   

   housing_units   gross_rent  
0       378401.0  2817.285714  
1       379050.0  3031.833333  
2       376454.0  2318.400000  
3       382295.0  3739.000000  
5       378076.5  2698.833333

Neighborhood       Lat         Lon     year  sale_price_sqr_foot  \
68         West Portal  37.74026 -122.463880  2012.25           498.488485   
69    Western Addition  37.79298 -122.435790  2012.50           307.562201   
70  Westwood Highlands  37.73470 -122.456854  2012.00           533.703935   
71       Westwood Park  37.73415 -122.457000  2015.00           687.087575   
72         Yerba Buena  37.79298 -122.396360  2012.50           576.709848   

    housing_units   gross_rent  
68      376940.75  2515.500000  
69      377427.50  2555.166667  
70      376454.00  2250.500000  
71      382295.00  3959.000000  
72      377427.50  2555.166667

### Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighborhoods_df` DataFrame. Be sure to do the following:

* Set the `geo` parameter to True.
* Set the `size` parameter to “sale_price_sqr_foot”.
* Set the `color` parameter to “gross_rent”.
* Set the `frame_width` parameter to 700.
* Set the `frame_height` parameter to 500.
* Include a descriptive title.

In [60]:
# Create a plot to analyse neighborhood info
# Plot the data using hvPlot and Geoviews
all_neighborhoods_df.hvplot.points(
    'Lon', 
    'Lat', 
    geo=True, 
    size = 'sale_price_sqr_foot',
    color='gross_rent',
    tiles='OSM',
    alpha = 0.8,
    frame_width = 700,
    frame_height = 500,
    title = "Interactive Neighborhood Map - By Sale Price per Square Foot"
    )

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (gross_rent,sale_price_sqr_foot)

### Use the interactive map to answer the following question

### Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?

* __The color density indicates the neighborhoods with the highest gross rent. Therefore, the neighborhoods where the color (here blue) is the darkest indicates the high gross rent neighborhoods.__

* __The size of the bubble in the chart indicate the areas with high sales price per square foot.__

## Compose Your Data Story

### How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighborhoods across San Francisco?

_The sales price has seen a constant upward trend across the years through different neighborhoods. Although the general analysis yielded a slight decrease in 2011. It has seen a constant upward trend through the other years. The rental income growth on the other hand has increased constantly at a higher rate across the years._

This trend does not apply to all neighborhoods in San Francisco. For example - The Alamo Square observed a downward trend in the sales price between 2015 to 2016 which was almost half the actual sales price mean.

The gross rent has quadrupled over the years which has been consistent across all neighborhoods.

### What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighborhoods exist that you would suggest for investment, and why?

_The "Neighborhood Analysis" can be used to identify areas with potential for investment. Using factors such as historical price trends in both sales price and gross rent._

* The neighborhoods that have shown consistent growth in sale prices per square foot over the years, indicate a strong real estate market.

* Neighborhoods with higher rental yields, offer better returns on investment.

* Looking into the housing units also gives a general overview of growing neighborhoods and indicates which are potentially good investment/purchase zones.
